namespace Game.Engine.ECS;

/// <summary>
///     Canonical shared-memory signal header — the C# half of the shared-memory signal
///     contract. The TypeScript half is generated by <c>Game.Engine.Generators</c> into
///     <c>src/Game.UI/Frontend/scenes/generated/signalLayout.ts</c>; the stride/scalar-size
///     constants are asserted at boot, never hand-synced.
///
///     Every signal buffer starts with a six-element standard header:
///         [0] seq, [1] epoch, [2] entityCount, [3] stride, [4] stepMs, [5] tickMs
///     followed by scene-specific scalar extras, then entityCount × stride entity records.
///     The scalar element type is per signal (see <c>SignalBufferLayout</c>): ecs/sprite-move
///     uses 4-byte floats, transform3d uses 8-byte doubles.
///     Booleans are encoded as 0 / 1.
/// </summary>
public static class SignalBuffer
{
    public const int HeaderLength = 6;
    public const int HeaderSeq = 0;
    public const int HeaderEpoch = 1;
    public const int HeaderEntityCount = 2;
    public const int HeaderStride = 3;
    public const int HeaderStepMs = 4;
    public const int HeaderTickMs = 5;

    public static void WriteHeader(
        Span<float> f, long seq, long epoch, int entityCount, int stride, double stepMs, double tickMs)
    {
        f[HeaderSeq] = seq;
        f[HeaderEpoch] = epoch;
        f[HeaderEntityCount] = entityCount;
        f[HeaderStride] = stride;
        f[HeaderStepMs] = (float)stepMs;
        f[HeaderTickMs] = (float)tickMs;
    }

    public static void WriteHeader(
        Span<double> f, long seq, long epoch, int entityCount, int stride, double stepMs, double tickMs)
    {
        f[HeaderSeq] = seq;
        f[HeaderEpoch] = epoch;
        f[HeaderEntityCount] = entityCount;
        f[HeaderStride] = stride;
        f[HeaderStepMs] = stepMs;
        f[HeaderTickMs] = tickMs;
    }
}

/// <summary>
///     Per-signal buffer geometry: element stride and scalar element size, one entry
///     per scene. Cross-checked against the <c>[TypeScriptExport]</c> structs by the
///     generated module-initializer.
/// </summary>
public static class SignalBufferLayout
{
    // ecs (sprite-move): no extras, SpriteState record (id, x, y, r, g, b) — float32.
    public const int EcsStride = 6;
    public const int EcsScalarSize = 4;
    public const int EcsByteLength = EcsStride * EcsScalarSize;

    // transform3d: no extras, Transform3DState record (id, xyz, quat xyzw, scale xyz) — float64.
    public const int Transform3DStride = 11;
    public const int Transform3DScalarSize = 8;
    public const int Transform3DByteLength = Transform3DStride * Transform3DScalarSize;
}

/// <summary>
///     Encoders for every batched render signal into the shared-memory layout consumed by
///     <c>DirectRenderTransport</c> and the TypeScript decoders. One
///     <c>ElementLength</c> + <c>Encode</c> pair per signal type; the transport sizes its
///     pinned buffer from <c>ElementLength</c> before calling <c>Encode</c>.
/// </summary>
public static class SignalBufferEncoders
{
    // ---- ECS (sprite-move): float32 buffer ---------------------------------

    public static int ElementLength(EcsRenderSignal s) =>
        SignalBuffer.HeaderLength + s.Sprites.Count * SignalBufferLayout.EcsStride;

    public static void Encode(EcsRenderSignal s, Span<float> f)
    {
        // EcsRenderSignal carries no StepMs/Epoch; the client's interpolation
        // header still expects them, so encode the fixed 60 Hz step and epoch 0.
        SignalBuffer.WriteHeader(f, s.Seq, 0, s.Sprites.Count,
            SignalBufferLayout.EcsStride, (1d / 60d) * 1000d, s.TickMs);
        WriteEntities(f, SignalBuffer.HeaderLength, s.Sprites, SignalBufferLayout.EcsStride,
            static (sp, dst) =>
            {
                dst[0] = sp.Id;
                dst[1] = sp.X;
                dst[2] = sp.Y;
                dst[3] = sp.R;
                dst[4] = sp.G;
                dst[5] = sp.B;
            });
    }

    // ---- 3D transforms (transform3d): float64 buffer ----------------------

    public static int ElementLength(Transform3DRenderSignal s) =>
        SignalBuffer.HeaderLength + s.States.Count * SignalBufferLayout.Transform3DStride;

    public static void Encode(Transform3DRenderSignal s, Span<double> f)
    {
        SignalBuffer.WriteHeader(f, s.Seq, 0, s.States.Count,
            SignalBufferLayout.Transform3DStride, (1d / 60d) * 1000d, s.TickMs);
        WriteEntities(f, SignalBuffer.HeaderLength, s.States, SignalBufferLayout.Transform3DStride,
            static (st, dst) =>
            {
                dst[0] = st.Id;
                dst[1] = st.X;
                dst[2] = st.Y;
                dst[3] = st.Z;
                dst[4] = st.Qx;
                dst[5] = st.Qy;
                dst[6] = st.Qz;
                dst[7] = st.Qw;
                dst[8] = st.Sx;
                dst[9] = st.Sy;
                dst[10] = st.Sz;
            });
    }

    // ---- shared writer --------------------------------------------------------

    private static void WriteEntities<TEntity, TElement>(
        Span<TElement> f, int entityBase, IReadOnlyList<TEntity> entities, int stride,
        WriteEntity<TEntity, TElement> write)
    {
        for (var i = 0; i < entities.Count; i++)
        {
            write(entities[i], f.Slice(entityBase + i * stride, stride));
        }
    }

    private delegate void WriteEntity<in TEntity, TElement>(TEntity entity, Span<TElement> destination);

    private static float Bool(bool value) => value ? 1f : 0f;
}
